apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-prod
  namespace: production
  labels:
    tier: production
    app: mongodb
spec:
  selector:
    app: mongodb
    tier: production
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
