apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-test
  namespace: test
  labels:
    tier: test
    app: mongodb
spec:
  selector:
    app: mongodb
    tier: test
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017