apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-test-claim
  namespace: test
  labels:
    tier: test
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi