apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy-prod
  namespace: production
  labels:
    app: react
    tier: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
      tier: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: react
        tier: test
    spec:
      containers:
      - name: react
        image: myuser/react
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: react-deploy-prod