apiVersion: v1
kind: Service
metadata:
  name: react-svc-prod
  namespace: production
  labels:
    tier: production
    app: react
spec:
  selector:
    app: react
    tier: production
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
