apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-prod-claim
  namespace: production
  labels:
    tier: production
    app: node
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi