apiVersion: v1
kind: Service
metadata:
  name: node-service-prod
  namespace: production
  labels:
    tier: production
    app: node
spec:
  type: NodePort
  selector:
    app: node
    tier: production
  ports:
  - port: 8080
    nodePort: 30001
