apiVersion: v1
kind: Service
metadata:
  name: node-service-test
  namespace: test
  labels:
    tier: test
    app: node
spec:
  type: NodePort
  selector:
    app: node
    tier: test
  ports:
  - port: 8080
    nodePort: 30001
