apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-test-claim
  namespace: test
  labels:
    tier: test
    app: node
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi